name: Master

on: 
   push:
     branches : 
       - master
   pull_request:
     branches : 
       - master

jobs:
  macos:

    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: use Setup-Scheme
      uses: guenchi/setup-scheme@master
      with:
        implementation: chez
           
    - name: install raven
      run: |
           cd /usr/local/bin
           cp chez scheme
           curl -L http://ravensc.com/install | scheme
           
    - name : test
      run: |
            git clone https://github.com/hinkelman/chez-docs
            cd chez-docs
            raven install srfi@1.0.0
            cd lib
            git clone https://github.com/hinkelman/chez-docs
            cd ..
            raven run test/tests.ss    
            
  ubuntu:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: use Setup-Scheme
      uses: guenchi/setup-scheme@master
      with:
        implementation: chez

    - name: install raven
      run: curl -L http://ravensc.com/install | sudo scheme
      
    - name : test
      run: |
            git clone https://github.com/hinkelman/chez-docs
            cd chez-docs
            raven install srfi@1.0.0
            cd lib
            git clone https://github.com/hinkelman/chez-docs
            cd ..
            raven run test/tests.ss
